# Use the official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

COPY package.json ./

# Install pnpm
RUN npm install 

# Copy the rest of the application code
COPY . .

RUN npm run build

# Expose the port the client runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start"]
