# Use the official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

COPY package.json ./

# Install pnpm
RUN npm install 

# Copy the rest of the application code
COPY . .

# Generate .env
RUN echo "NEXT_PUBLIC_API_URL=https://huawei-poc-server-203649101776.us-central1.run.app" > .env

RUN npm run build

# Expose the port the client runs on
EXPOSE 3000


# Command to run the application
CMD ["npm", "run", "start"]
