services:
  client:
    image: hw-client:latest
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  server:
    image: hw-server:latest
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
