services:
  client:
    image: hw-client:latest
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://35.185.182.204:8081

  server:
    image: hw-server:latest
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
